ALTER TABLE note_meta
  ADD COLUMN IF NOT EXISTS place_name TEXT,
  ADD COLUMN IF NOT EXISTS place_display_name TEXT,
  ADD COLUMN IF NOT EXISTS place_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS place_lon DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS osm_url TEXT;
