ALTER TABLE film_meta
  ADD COLUMN IF NOT EXISTS ia_identifier TEXT,
  ADD COLUMN IF NOT EXISTS ia_title TEXT,
  ADD COLUMN IF NOT EXISTS ia_year TEXT,
  ADD COLUMN IF NOT EXISTS ia_page_url TEXT,
  ADD COLUMN IF NOT EXISTS ia_file_url TEXT,
  ADD COLUMN IF NOT EXISTS ia_checked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ia_downloaded_path TEXT;
